- CHANGES_NEXT_RELEASE
- README.md
> ADD Documentation about transport bindings

- CHANGES_NEXT_RELEASE
- README.md
- lib/ulParser.js
- test/unit/httpBinding-test.js
- test/unit/mqttBinding-test.js
- test/unit/ultralightMeasures-test.js
> FIX Measure format for Ultralight

- CHANGES_NEXT_RELEASE
- sonar-project.properties
> ADD Sonar files for static analysis

- Dockerfile
- README.md
- config-blank.js
> ADD Dockerfile for the agent

- rpm/SOURCES/etc/init.d/iotaUL
He añadido un par de lineas para que las variables del script del servicio se puedan reescribir.
> added variable override by additional config file

- config.js
- package.json
> FIX Config file and logops version

- bin/iotaULTester.js
- config.js
- package.json
Fix errors found in the integration of the Agent with the rest of the components of the platform.
> FIX Error found in integration tests

- CHANGES_NEXT_RELEASE
- config.js
- lib/bindings/HTTPBindings.js
- lib/bindings/MQTTBinding.js
- lib/iotagent-ul.js
- test/config-test.js
- test/contextRequests/updateStatus1.json
- test/contextRequests/updateStatus2.json
- test/deviceProvisioning/provisionCommand1.json
- test/deviceProvisioning/provisionCommand2.json
- test/unit/commandsHTTP-test.js
- test/unit/commandsHttp-test.js
> ADD transport protocol to distinguish between transports

- lib/bindings/HTTPBindings.js
- lib/bindings/MQTTBinding.js
- package.json
Add service and subservice information for requests coming from the Southbound (by bounding it to the domain(.
> ADD TransactionInformationInSouthbound

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBindings.js
> ADD IPv6 for Southbound API

- CHANGES_NEXT_RELEASE
- config.js
- lib/bindings/MQTTBinding.js
- test/unit/mqttBinding-test.js
> FIX Die when an unexpected payload arrives

- README.md
> FIX Wrong topics in doc

- CHANGES_NEXT_RELEASE
- lib/ulParser.js
- test/contextRequests/updateCommand3.json
- test/contextRequests/updateStatus3.json
- test/deviceProvisioning/provisionCommand3.json
- test/deviceProvisioning/provisionGroup1.json
- test/unit/commandsMqtt-test.js
- test/unit/ultralitghtCommands-test.js
> ADD Single values for commands

- CHANGES_NEXT_RELEASE
- README.md
> FIX Documentation about docker hub repos

- CHANGES_NEXT_RELEASE
- lib/bindings/MQTTBinding.js
> ADD Wildcards for MQTT subscriptions

- README.md
- config-blank.js
Change the default log level for Docker configurations.
> Change the default log level

- CHANGES_NEXT_RELEASE
- config.js
- lib/bindings/MQTTBinding.js
- lib/ulParser.js
- test/unit/ultralightMeasures-test.js
> FIX empty payload raises exception

- CHANGES_NEXT_RELEASE
- config.js
- lib/bindings/HTTPBindings.js
- lib/bindings/MQTTBinding.js
- test/config-test.js
Fixes bug found in integration.
> FIX mixed up apikey and resource

- .travis.yml
Update Node.js version to latest 4.x in Travis CI tests.
> Update Node.js version to latest 4.x

- bin/iotagent-ul
- config.js
- lib/bindings/MQTTBinding.js
> ADD Log traces

- CHANGES_NEXT_RELEASE
- README.md
- lib/configService.js
- test/unit/startup-test.js
> FIX Add prefix for environment variables

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBindings.js
- lib/iotagent-ul.js
- test/contextRequests/timestampMeasure.json
- test/unit/httpBinding-test.js
> ADD Missing timestamp

- lib/iotagent-ul.js
Add Event plugin for the IOTA UL
> ADD Event plugin

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBindings.js
- test/config-test.js
- test/contextRequests/unprovisionedMeasure.json
- test/contextResponses/unprovisionedSuccess.json
- test/groupProvisioning/provisionFullGroup.json
- test/unit/httpBinding-test.js
> ADD Automatic registration of unprovisioned devices

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBindings.js
- test/unit/httpBinding-test.js
> ADD Default content-type header

- CHANGES_NEXT_RELEASE
- README.md
- lib/ulParser.js
- test/unit/ultralightMeasures-test.js
> ADD Optional timestamp for measure groups

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
- test/contextRequests/unprovisionedAliasMeasure.json
- test/contextResponses/unprovisionedAliasSuccess.json
- test/groupProvisioning/provisionAliasGroup.json
- test/unit/httpBinding-test.js
> ADD Merge configuration values with device values in measure reporting

- rpm/SOURCES/etc/init.d/iotaul
Fijado error cuando la instancia no se encontraba y además añadido mensaje.
> added error message when instance is not found

- CHANGES_NEXT_RELEASE
- bin/iotaULTester.js
- client-config.js
> ADD HTTP Testing commands to the command line client

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBindings.js
- lib/errors.js
- test/contextRequests/updateCommandWrongEndpoint.json
- test/contextRequests/updateStatusError.json
- test/deviceProvisioning/provisionCommandWrongEndpoint.json
- test/unit/commandsHTTP-test.js
- test/unit/commandsHttp-test.js
When a connection error was received by a command, the error reporting process would fail, and the command would be stuck in PENDING state forever.
> FIX Commands failing to write error result in the CB

- CHANGES_NEXT_RELEASE
- config.js
- lib/bindings/HTTPBindings.js
- package.json
> ADD Timeout for command calls

- rpm/SOURCES/etc/init.d/iotaul
Fix service init script don't finding environment variables.
> FIX Initial service command

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBindings.js
Fix small error in the debug log.
> FIX Error info not decoded

- package.json
FIX IoTALib version with wildcards
> FIX IoTALib version with wildcards

- CHANGES_NEXT_RELEASE
- test/contextRequests/timeInstantDuplicated.json
- test/contextResponses/timeInstantDuplicatedSuccess.json
- test/deviceProvisioning/provisionTimeInstant.json
- test/unit/httpBinding-test.js
- test/unit/mqttBinding-test.js
Fixes #150
Doesn't replicate the bug, that was found for older versions of the Agent. Added tests to ensure the IoTA Behaves properly for future references.
> FIX Duplicated TimeInstant

- rpm/SOURCES/etc/init.d/iotaul
Añadido username para no parchear el script de inicio del servicio con los Ansible de despliegue
> added missing username

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBindings.js
- lib/errors.js
- test/contextRequests/updateStatusError2.json
- test/contextResponses/updateStatusError2Success.json
- test/unit/commandsHTTP-test.js
- test/unit/commandsHttp-test.js
> FIX Command error response message

- CHANGES_NEXT_RELEASE
- lib/iotagent-ul.js
> FIX Missing metadata in expressions

- docs/operations.md
to comply with the operations guys
> added a Severity field

- npm-shrinkwrap.json
- rpm/SPECS/iotaul.spec
Add npm-shrinkwrap.json file in master branch and adjust .spec to take it into account at RPM generation time.
@vgarciag
> FIX shrinkwrap aspects

- CHANGES_NEXT_RELEASE
- npm-shrinkwrap.json
- package.json
- rpm/SPECS/iotaul.spec
See  https://github.com/telefonicaid/iotagent-ul/commit/208f55eec5903fc10a9ccaa5a1279efce8805f59 to check the steps are the same (in addition to the new one regarding npm-shrinkwrap.json)
> ADD Step: 1.4.0-next -> 1.5.0

- npm-shrinkwrap.json
- package.json
Same as PR https://github.com/telefonicaid/iotagent-ul/pull/228
> Step: 1.6.0 -> 1.6.0-next

- CHANGES_NEXT_RELEASE
- npm-shrinkwrap.json
Docker image deps relies on that file
> update npm_shrinkwrap file

- CHANGES_NEXT_RELEASE
- config-blank.js
- config.js
- docs/installationguide.md
- lib/bindings/MQTTBinding.js
- lib/configService.js
issue https://github.com/telefonicaid/iotagent-ul/issues/255
> enable qos=2 and retain=true in mqtt binding

- lib/bindings/MQTTBinding.js
- npm-shrinkwrap.json
> check boolean field against boolean value

- docs/usermanual.md
Based on recent dicussion on issue https://github.com/telefonicaid/iotagent-ul/issues/271
@dcalvoalonso could you have a look and review, please? Thx!
> FIX doc regarding autocast feature

- lib/configService.js
CNR is already including info abbout new mqtt.retain option
> check boolean value of mqtt.retain env var

- config.js
- docs/installationguide.md
- lib/bindings/AMQPBinding.js
- lib/configService.js
reopen PR https://github.com/telefonicaid/iotagent-ul/pull/280
fix issue https://github.com/telefonicaid/iotagent-ul/issues/268
> add AMQP user pass conf env vars

- docs/installationguide.md
- lib/bindings/AMQPBinding.js
- lib/configService.js
- lib/constants.js
> add amqp retry conf

- .dockerignore
- Dockerfile
* Save `Dockerfile` as UTF-8 - to correct the `MAINTAINER`  Telefónica I+D
* Add `.dockerignore` file
* Use an `ARG` to set the node version
> Minor Dockerfile fix

- .travis.yml
This PR is aligned with https://github.com/telefonicaid/iotagent-node-lib/pull/707#issuecomment-439799728
> Runs lint check in travis

- CHANGES_NEXT_RELEASE
- config.js
- docs/installationguide.md
- lib/bindings/HTTPBindings.js
- lib/configService.js
> Timeout for HTTP commands

- CHANGES_NEXT_RELEASE
- docker/Dockerfile
> Update Node Version

- README.md
- docs/roadmap.md
Fixes https://github.com/telefonicaid/iotagent-ul/issues/337
@dcalvoalonso could you have a look and provide LGTM if ok, pls? Thanks!
> Add roadmap document

- README.md
> Add AGPL disclaimer

- docker/Dockerfile
> Expose PORTS Added

- bin/iotaULTester.js
- docker/Dockerfile
- docker/README.md
- docs/installationguide.md
- test/config-test.js
- test/subscriptionRequests/bidirectionalSubscriptionRequest.json
- test/unit/amqpBinding-test.js
- test/unit/httpBinding-test.js
- test/unit/mqttBinding-test.js
- test/unit/ngsiv2/amqpBinding-test.js
- test/unit/ngsiv2/config-test.js
- test/unit/ngsiv2/httpBindings-test.js
- test/unit/ngsiv2/mqttBinding-test.js
- test/unit/ngsiv2/subscriptionRequests/bidirectionalSubscriptionRequest.json
According to https://github.com/telefonicaid/iotagent-ul/blob/master/config.js#L119 default port for this agent is 4061. This PR fix it in Docker related stuff.
@jason-fox could you review? (Maybe I have missed some piece to update...) Thanks!
> FIX default port in Dockerfile and related stuff

- config.js
- docker/Dockerfile
- docker/README.md
- docker/entrypoint.sh
- docker/hooks/build
The second phase of PR https://github.com/telefonicaid/iotagent-ul/pull/339. As sanity check, the +196 -9 diff checksum is exactly the same.
A CI e2e regression will be conducted with a docker container generated on this branch. If everything goes ok (I don't expect any problem) the PR will be merged.
CC: @jason-fox
> Feature/docker secrets (second phase)

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
> Step: 1.8.0-next -> 1.9.0

- .travis.yml
- CHANGES_NEXT_RELEASE
- README.md
- package.json
Mimics PR https://github.com/telefonicaid/iotagent-json/pull/400
> REMOVE node v6 ADD node v12

- config.js
- docs/installationguide.md
fixes https://github.com/telefonicaid/iotagent-ul/issues/374
No CNR update
> update MQTT doc

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
> Step: 1.9.0-next -> 1.10.0

- CHANGES_NEXT_RELEASE
- lib/bindings/MQTTBinding.js
twin PR: https://github.com/telefonicaid/iotagent-json/pull/438
> check callback before use it

- CHANGES_NEXT_RELEASE
- lib/bindings/AMQPBinding.js
- lib/bindings/MQTTBinding.js
- lib/iotagent-ul.js
Fix twin issue at IOTAgent-json [#409](https://github.com/telefonicaid/iotagent-json/issues/409)
> Updated files for AMQP/MQTT connections

- test/unit/ngsiv2/bidirectionalityHttp-test.js
- test/unit/ngsiv2/subscriptionRequests/bidirectionalSubscriptionRequest.json
Related with telefonicaid/iotagent-node-lib#822
> FIX broken utest after telefonicaid/iotagent-node-lib#822

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
> Step: 1.10.0-next -> 1.11.0

- docs/installationguide.md
Mimics PR https://github.com/telefonicaid/iotagent-json/pull/460
> FIX keepalive description in doc

- CHANGES_NEXT_RELEASE
- lib/commonBindings.js
twin PR https://github.com/telefonicaid/iotagent-json/pull/465
> log error -> log warn when device of apikey is not found

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
> Step: 1.12.0-next -> 1.13.0

- package.json
> Step: 1.13.0 -> 1.13.0-next

- CHANGES_NEXT_RELEASE
- config.js
- lib/commonBindings.js
- package.json
- test/unit/ngsiv2/contextRequests/timeInstantMeasures.json
- test/unit/ngsiv2/contextRequests/timeInstantMeasures2.json
- test/unit/ngsiv2/deviceProvisioning/provisionDeviceTimeinstant.json
- test/unit/ngsiv2/deviceProvisioning/provisionDeviceTimeinstant2.json
- test/unit/ngsiv2/httpBindings-test.js
Add the feature "selectively ignore some measure"
*Edit*: issue #372
> fixed for implementation of selectively ignore some measure issue#372

- docs/usermanual.md
Update document for issue #432, This is a twin issue of iotagent-json [224](https://github.com/telefonicaid/iotagent-json/issues/224)
> Update document for issue #432

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
depends on https://github.com/telefonicaid/iotagent-node-lib/pull/899
> get device silently

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBindings.js
- lib/commonBindings.js
depends on https://github.com/telefonicaid/iotagent-node-lib/pull/901
> force to finish southbound transaction

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
> step 1.13.0-next -> 1.14.0

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
twin PR from https://github.com/telefonicaid/iotagent-json/pull/502/
> check ngsi version before read configuration response

- lib/iotaUtils.js
Twin PR https://github.com/telefonicaid/iotagent-json/pull/506
> check ngsi to process response

- CHANGES_NEXT_RELEASE
- docs/usermanual.md
- lib/bindings/MQTTBinding.js
twin PR https://github.com/telefonicaid/iotagent-json/pull/507/
needs PR https://github.com/telefonicaid/iotagent-node-lib/pull/925
> use command mqtt conf

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
> step 1.14.0-next -> 1.15.0

- CHANGES_NEXT_RELEASE
- config.js
- docs/installationguide.md
fix for https://github.com/telefonicaid/iotagent-ul/issues/370
> set 60 default keepalive

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
> step 1.15.0-next -> 1.16.0

- README.md
Added CII Best Practices Badge to README file
Pending https://github.com/telefonicaid/iotagent-ul/pull/468 to fill the requirements needed for the badge
> Added CII Best Practices Badge to README file

- docs/contribution.md
Creating contribution.md file in order to be aligned with CII Best Practices
> Create contribution.md file

- CHANGES_NEXT_RELEASE
- docs/usermanual.md
- lib/configService.js
> Add protected variables

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
- test/unit/ngsiv2/HTTP_commands_test.js
- test/unit/ngsiv2/MQTT_commands_test.js
- test/unit/ngsiv2/amqpBinding-test.js
- test/unit/ngsiv2/commandsAmqp-test.js
- test/unit/ngsiv2/commandsPolling-test.js
- test/unit/ngsiv2/contextRequests/updateStatus2.json
- test/unit/ngsiv2/httpBindings-test.js
- test/unit/ngsiv2/mqttBinding-test.js
depends on telefonicaid/iotagent-node-lib#1061
> check autoprovision flag before register device

- CHANGES_NEXT_RELEASE
- lib/commonBindings.js
twin PR https://github.com/telefonicaid/iotagent-json/pull/577
> check active attributes before accese them

- CHANGES_NEXT_RELEASE
It seems the number was wrong. @mapedraza please check
> FIX issue number in CHANGES_NEXT_RELEASE

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
Mimics PR https://github.com/telefonicaid/iotagent-ul/pull/494
> Step: 1.17.0-next -> 1.18.0

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
> Step: 1.18.0-next -> 1.19.0

- package.json
> Step: 1.19.0 -> 1.19.0-next

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
fix for https://github.com/telefonicaid/iotagent-node-lib/issues/1155
> provide device type to findCOnfiguration to achieve a better group match

- CHANGES_NEXT_RELEASE
- docs/operations.md
- lib/commonBindings.js
issue https://github.com/telefonicaid/iotagent-ul/issues/530
> try handle non string message as hex 

- docs/usermanual.md
To make this same as in the IOTA-JSON documentation.
> FIX command documentation

- CHANGES_NEXT_RELEASE
- lib/commonBindings.js
twin PR of https://github.com/telefonicaid/iotagent-json/pull/643
> fix bad ul message when multiple measures

- CHANGES_NEXT_RELEASE
- docs/usermanual.md
- lib/bindings/AMQPBinding.js
- lib/ulParser.js
Issues: https://github.com/telefonicaid/iotagent-json/issues/634 https://github.com/telefonicaid/iotagent-json/issues/627
related and needs https://github.com/telefonicaid/iotagent-node-lib/pull/1209
The possible payload transformations are: 
https://github.com/telefonicaid/iotagent-ul/blob/243b2807aad41880ec911fd8ca8fe2e19b5cbfb2/lib/ulParser.js#L243-L257
> add expressions and payload transformations to commands

- CHANGES_NEXT_RELEASE
- docs/usermanual.md
- lib/bindings/MQTTBinding.js
- package.json
- issue related https://github.com/telefonicaid/iotagent-json/issues/650
- Twin PR https://github.com/telefonicaid/iotagent-json/pull/651
> fix publishing commands

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
> Step: 1.20.0-next -> 1.21.0

- package.json
> step 1.21.0 -> 1.21.0-next

- CHANGES_NEXT_RELEASE
- lib/ulParser.js
- test/deviceProvisioning/provisionCommand7.json
- test/unit/ngsiv2/HTTP_commands_test.js
- test/unit/ngsiv2/contextRequests/updateCommand2.json
twin PR of https://github.com/telefonicaid/iotagent-json/pull/671
> include id, type, service and subservice in ctxt for evaluate expresion in command

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
Mimics PR https://github.com/telefonicaid/iotagent-ul/pull/558
> step 1.21.0-next -> 1.22.0

- package.json
Mimics PR https://github.com/telefonicaid/iotagent-ul/pull/559
> step 1.22.0 -> 1.22.0-next

- CHANGES_NEXT_RELEASE
- lib/bindings/MQTTBinding.js
twin PR https://github.com/telefonicaid/iotagent-json/pull/682
> handle error ending mqttClient

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
> Step: 1.23.0-next -> 1.24.0

- package.json
> Step: 1.24.0 -> 1.24.0-next

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
- test/unit/ngsiv2/amqpBinding-test.js
- test/unit/ngsiv2/explicit_attributes-test.js
- test/unit/ngsiv2/groupProvisioning/provisionAliasGroup.json
- test/unit/ngsiv2/groupProvisioning/provisionFullGroup.json
- test/unit/ngsiv2/groupProvisioning/provisionFullGroupAMQP.json
- test/unit/ngsiv2/httpBindings-test.js
- test/unit/ngsiv2/mqttBinding-test.js
related and needs telefonicaid/iotagent-node-lib#1275
> use group apikey for autoprovision device

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
Mimics PR https://github.com/telefonicaid/iotagent-ul/pull/575
> Step: 1.24.0-next -> 1.25.0

- package.json
Mimics PR https://github.com/telefonicaid/iotagent-ul/pull/577
> Step: 1.25.0 -> 1.25.0-next

- docs/usermanual.md
This PR modifies the doc in order to align it after changes in https://github.com/telefonicaid/iotagent-node-lib/pull/1324
> Modify autocast doc according #iotagent-node-lib/1324

- docs/usermanual.md
> Add str example to autocast doc according #iotagent-node-lib/1324 #591

- package.json
> step 2.0.0 -> 2.0.0-next

- CHANGES_NEXT_RELEASE
- package.json
- rpm/SPECS/iotaul.spec
> Step: 2.0.0-next -> 2.1.0

- package.json
> Step: 2.1.0 -> 2.1.0-next

- test/deviceProvisioning/provisionCommandBidirectional.json
- test/deviceProvisioning/provisionCommandBidirectionalWithUrl.json
- test/unit/ngsiv2/bidirectionalityHttp-test.js
This PR fix bidirectionality tests after https://github.com/telefonicaid/iotagent-node-lib/pull/1339 
Mimics https://github.com/telefonicaid/iotagent-json/pull/719
> Fix bidirectionality tests

- package.json
- rpm/SPECS/iotaul.spec
> step 2.1.0-next -> 2.2.0

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
related https://github.com/telefonicaid/iotagent-node-lib/pull/1391
> do not propage config flags from group to unprovisioned device

- CHANGES_NEXT_RELEASE
- Changelog
- test/unit/ngsiv2/HTTP_commands_test.js
- test/unit/ngsiv2/MQTT_commands_test.js
- test/unit/ngsiv2/amqpBinding-test.js
- test/unit/ngsiv2/commandsAmqp-test.js
- test/unit/ngsiv2/commandsPolling-test.js
- test/unit/ngsiv2/contextRequests/multipleMeasure.json
- test/unit/ngsiv2/contextRequests/multipleMeasureProduction.json
- test/unit/ngsiv2/contextRequests/multipleMeasuresTypeJson.json
- test/unit/ngsiv2/contextRequests/pollingMeasure.json
- test/unit/ngsiv2/contextRequests/secondMultipleMeasure.json
- test/unit/ngsiv2/contextRequests/secondSingleMeasure.json
- test/unit/ngsiv2/contextRequests/singleMeasure.json
- test/unit/ngsiv2/contextRequests/timeInstantDuplicated.json
- test/unit/ngsiv2/contextRequests/timeInstantMeasures.json
- test/unit/ngsiv2/contextRequests/timeInstantMeasures2.json
- test/unit/ngsiv2/contextRequests/timestampMeasure.json
- test/unit/ngsiv2/contextRequests/unprovisionedAliasMeasure.json
- test/unit/ngsiv2/contextRequests/unprovisionedAliasMeasure2.json
- test/unit/ngsiv2/contextRequests/unprovisionedMeasure.json
- test/unit/ngsiv2/contextRequests/updateStatus1.json
- test/unit/ngsiv2/contextRequests/updateStatus2.json
- test/unit/ngsiv2/contextRequests/updateStatus3.json
- test/unit/ngsiv2/contextRequests/updateStatus4.json
- test/unit/ngsiv2/contextRequests/updateStatus5.json
- test/unit/ngsiv2/contextRequests/updateStatus6.json
- test/unit/ngsiv2/explicit_attributes-test.js
- test/unit/ngsiv2/httpBindings-test.js
- test/unit/ngsiv2/mqttBinding-test.js
depens on https://github.com/telefonicaid/iotagent-node-lib/pull/1111
> Update tests to use upsert

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/advanced-issue-labeler.yml
- .github/workflows/issue-labeler.yml
Twin PR https://github.com/telefonicaid/iotagent-node-lib/pull/1379
> Add issue template

- CHANGES_NEXT_RELEASE
- test/unit/ngsiv2/HTTP_commands_test.js
- test/unit/ngsiv2/MQTT_commands_test.js
- test/unit/ngsiv2/amqpBinding-test.js
- test/unit/ngsiv2/commandsAmqp-test.js
- test/unit/ngsiv2/commandsPolling-test.js
- test/unit/ngsiv2/configurationsMqtt-test.js
- test/unit/ngsiv2/explicit_attributes-test.js
- test/unit/ngsiv2/httpBindings-test.js
- test/unit/ngsiv2/mqttBinding-test.js
related and needs https://github.com/telefonicaid/iotagent-node-lib/pull/1390
> remove mock about initial entity

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> Task/prepare 2.3.0

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
related https://github.com/telefonicaid/iotagent-node-lib/issues/1430
> ensure apikey in device

- CHANGES_NEXT_RELEASE
- lib/iotaUtils.js
twin PR https://github.com/telefonicaid/iotagent-json/pull/743
> use apikey to find, update and remove device

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> step 2.3.0-next -> 2.4.0

- package.json
> step 2.4.0-next

- lib/bindings/AMQPBinding.js
- lib/bindings/HTTPBindings.js
- lib/bindings/MQTTBinding.js
continuation of PR https://github.com/telefonicaid/iotagent-ul/pull/637
Using the same CNR entry
> fix srv and subservice in logs about bindings

- CHANGES_NEXT_RELEASE
- lib/commonBindings.js
- lib/ulParser.js
- test/unit/ngsiv2/config-test.js
- test/unit/ngsiv2/ultralightMeasures-test.js
Needed by https://github.com/telefonicaid/iotagent-ul/pull/639 and https://github.com/telefonicaid/iotagent-node-lib/pull/1501
> remove autocast feature from iotagent-ul

- docs/usermanual.md
- test/unit/ngsiv2/config-test.js
Related:
https://github.com/telefonicaid/iotagent-node-lib/pull/1501
> Remove autocast references

- lib/commonBindings.js
related and continuation of https://github.com/telefonicaid/iotagent-ul/pull/644
aligned with iota-json: 
https://github.com/telefonicaid/iotagent-json/blob/70399b7491da3ac0b31c40e1bd5a430dc413a64a/lib/commonBindings.js#L80-L87
> check device.active

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> step 2.4.0-next -> 3.0.0

- package.json
> step 3.0.0-next

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> step 3.0.0-next -> 3.1.0

- package.json
> step 3.1.0 -> 3.1.0-next

- docs/requirements.txt
See PR https://github.com/telefonicaid/fiware-orion/pull/4475
> FIX mkdocs version

- Changelog
- package.json
> step 3.1.0-next -> 3.2.0

- CHANGES_NEXT_RELEASE
- lib/constants.js
- test/unit/ngsiv2/contextRequests/pollingMeasure.json
- test/unit/ngsiv2/contextRequests/timeInstantMeasures.json
- test/unit/ngsiv2/explicit_attributes-test.js
> default attribute type changed to Text

- test/deviceProvisioning/provisionDeviceProduction.json
> Added Timestamp attribute

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> step prepare 3.3.0

- package.json
> step prepare 3.3.0 next

- CHANGES_NEXT_RELEASE
- package.json
Similar to PR https://github.com/telefonicaid/iotagent-manager/pull/334
> FIX upgrade express dep from ~4.16.4 to 4.19.2

- CHANGES_NEXT_RELEASE
- lib/bindings/HTTPBindings.js
twin PR https://github.com/telefonicaid/iotagent-json/pull/828
> set express limit from iota config

- CHANGES_NEXT_RELEASE
- lib/bindings/AMQPBinding.js
- lib/bindings/HTTPBindings.js
- lib/bindings/MQTTBinding.js
- lib/iotagent-ul.js
- test/unit/ngsiv2/HTTP_update_device_test.js
- test/unit/ngsiv2/deviceProvisioning/provisionDeviceHTTP4.json
- test/unit/ngsiv2/deviceProvisioning/updateProvisionDevice4.json
Twin PR of https://github.com/telefonicaid/iotagent-json/pull/834/
needs https://github.com/telefonicaid/iotagent-node-lib/pull/1616
> use oldDevice apikey when update device

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> prepare 3.5.0

- package.json
> step 3.5.0 -> 3.5.0-next

- CHANGES_NEXT_RELEASE
- Changelog
- package.json
> step 3.5.0 -> 3.6.0

- package.json
> step 3.6.0 -> 3.6.0-next

- .github/workflows/ci.yml
Mimics https://github.com/telefonicaid/iotagent-json/pull/849/
> Update ci.yml: remove nodejs 14

- package.json
> step 3.7.0 -> 3.7.0-next
