telefonicaid/iotagent-ul

bin/iotaULTester.js, lib/bindings/HTTPBindings.js, lib/bindings/MQTTBinding.js, lib/iotagent-ul.js, test/contextRequests/updateCommand1.json
- Add some log traces to aid in debugging the agent.
- Add a `sendMQTTCommand` for the command line interpreter.
- Change the payload of the commands from stringified JSON to plain objects.
=> ADD Log traces for debugging

lib/iotagent-ul.js
Fix the different log type (JSON or Pipe) for the library and the IOTA log.
=> FIX Different log type in libraries and general logs

lib/iotagent-ul.js
HTTP Provisioning handler raised an error, passing an array to the device provisioning handler callback.
=> FIX Provisioning handler raising errors

docs/usermanual.md
please avoid <a name> anchors, as anchors are created automatically as per the naming schema suggested by this PR.
=> Fix links user manual

package.json
to prevent several errors running `grunt test`
=> fix nock to 7.0.2

CHANGES_NEXT_RELEASE, npm-shrinkwrap.json, package.json, rpm/SPECS/iotaul.spec
Similar to https://github.com/telefonicaid/iotagent-ul/pull/227
However, npm-shrinkwrap.json generation has been improved based in the following procedure
```
rm -rf node_modules
rm npm-shrinkwrap.json
npm install
npm shrinkwrap
```
executed in the reference CentOS 6 jenkins which used:
```
$ node --version
v4.8.4
$ npm --version
2.15.11
```
=> Step: 1.5.0-next -> 1.6.0

CHANGES_NEXT_RELEASE, package.json, rpm/SPECS/iotaul.spec
Similar to PR https://github.com/telefonicaid/iotagent-ul/pull/247 (except npm-shrinkwrap.json generation, that is no longer include in the repository)
=> Step: 1.6.0-next -> 1.7.0

docs/installationguide.md, docs/operations.md, docs/usermanual.md
* The ToC is suppressed with the ReadtheDocs CSS
* The ToC Header cannot be suppressed without CSS3
Therefore the title of the ToC should be removed to avoid confusion
* Add `bash` code hints where not found
Readthedocs can mis-diagnose code styles sometimes.
Related to telefonicaid/iotagent-node-lib/issues/648
=> Remove `##Index` from ToC since it is not required

test/unit/amqpBinding-test.js, test/unit/httpBinding-test.js, test/unit/mqttBinding-test.js, test/unit/ngsiv2/amqpBinding-test.js, test/unit/ngsiv2/httpBindings-test.js, test/unit/ngsiv2/mqttBinding-test.js
Similar to https://github.com/telefonicaid/iotagent-json/pull/354
Please @dcalvoalonso could you review?
=> FIX broken unit test due to recent changes in iotagent-node-lib module

CHANGES_NEXT_RELEASE, docker/README.md, docker/entrypoint.sh
This PR is a potential fix for https://github.com/telefonicaid/iotagent-node-lib/issues/790
* Update entrypoint to use/not use pm2
* Add `PM2_ENABLED` to Docker README
* Update CNR.
=> Add PM2_ENABLED flag to Docker

docker/README.md, docker/entrypoint.sh
Once Mongo-DB  User and Password are fully supported within the iot-node-lib, they should be made available obfuscated within Docker 
Related: https://github.com/telefonicaid/iotagent-node-lib/pull/852
=> Add AMPQ, MQTT and Mongo-DB User and Password as Docker Secrets

CHANGES_NEXT_RELEASE, config.js, docs/installationguide.md, lib/bindings/HTTPBindings.js, lib/bindings/MQTTBinding.js, lib/configService.js, package.json, test/unit/startup-test.js
- Allow HTTP endpoint to be configured with a cert and a private key
- Allow self signed certs when using MQTT with SSL
- Update documentation
=> Add Southbound HTTPS support + Standardize MQTT

lib/bindings/MQTTBinding.js
API key and device id was mixed up in logged message
=> fix: change order of arguments to correspond with message

CHANGES_NEXT_RELEASE, lib/commonBindings.js, package.json
Fixed issue #326 for iotagent-ul that logs always write the same correlator id and transaction id.
=> Fix: Log always write the same correlator id and transaction id

lib/commonBindings.js, lib/iotaUtils.js
Related https://github.com/telefonicaid/iotagent-node-lib/issues/963
Note: the `isCurrentNgsi()` can be removed once NGSI-v1 is dropped.
=> Replace checkNgsi2 with isCurrentNgsi

.github/workflows/ci.yml, CHANGES_NEXT_RELEASE, docker/Dockerfile, docs/deprecated.md, package.json
With the recent release, Node 10 can be fully removed for the next release. No rush to merge this, just raising it whilst I remember to do it.
=> Fully Remove Node 10

lib/bindings/AMQPBinding.js, test/unit/amqpBinding-test.js, test/unit/commandsAmqp-test.js, test/unit/ngsiv2/amqpBinding-test.js, test/unit/ngsiv2/commandsAmqp-test.js
Replace `new Buffer()` with `Buffer.from()` - see https://stackoverflow.com/questions/52165333/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues
This is has been an issue from Node 10 onwards.
=> DeprecationWarning: Buffer() is deprecated due to security and usability issues.

CHANGES_NEXT_RELEASE, lib/iotaUtils.js
needs https://github.com/telefonicaid/iotagent-node-lib/pull/1002
for avoid raise a mongo alarm like
```
time=2021-03-11T08:01:17.133Z | lvl=DEBUG | corr=2efa0453-e1a4-4fbc-9009-b8428edf08fd | trans=2efa0453-e1a4-4fbc-9009-b8428edf08fd | op=IOTAUL.Common.Binding | from=n/a | srv=n/a | subsrv=n/a | msg=message topic: /kz8i86f13itd4ibff87secf8c/test1/attrs/v | comp=IoTAgent
time=2021-03-11T08:01:17.134Z | lvl=DEBUG | corr=2efa0453-e1a4-4fbc-9009-b8428edf08fd | trans=2efa0453-e1a4-4fbc-9009-b8428edf08fd | op=IoTAgentNGSI.MongoDBGroupRegister | from=n/a | srv=n/a | subsrv=n/a | msg=Looking for group params ["resource","apikey"] with queryObj {"resource":"/iot/d","apikey":"kz8i86f13itd4ibff87secf8c"} | comp=IoTAgent
time=2021-03-11T08:01:17.148Z | lvl=DEBUG | …
```
=> use get configuration silently

package.json, rpm/SPECS/iotaul.spec
relies on telefonicaid/iotagent-node-lib#1015
=>  Step: 1.16.0 -> 1.16.1 

CHANGES_NEXT_RELEASE, lib/iotaUtils.js
related with https://github.com/telefonicaid/iotagent-node-lib/pull/1029
=> use expressionLanguage from group if not defined in device

CHANGES_NEXT_RELEASE, lib/iotaUtils.js
PR to fix the problems reported here https://github.com/telefonicaid/iotagent-ul/pull/493#discussion_r654531005
The problem is in NGSIv2, the value of results is different depending if it is triggered by: 
- Context Request (configuration|pollingInterval|publishInterval), having the following value: `{"type":"number","value":"200","metadata":{}},"publishInterval":{"type":"number","value":"80","metadata":{}}}`
- Context Notification (subscription|pollingInterval|publishInterval), having the following value: `[{"type":"string","value":"60","name":"pollingInterval"},{"type":"number","value":"600","name":"publishInterval"}]`
=> Fix: Processing configurations subscriptions in NGSIv2 

test/unit/ngsiv2/HTTP_commands_test.js, test/unit/ngsiv2/MQTT_commands_test.js, test/unit/ngsiv2/configurationsMqtt-test.js, test/unit/ngsiv2/contextRequests/updateCommandWrongEndpoint.json, test/unit/ngsiv2/contextRequests/updateStatusError1.json, test/unit/ngsiv2/contextRequests/updateStatusError2.json, test/unit/ngsiv2/contextResponses/getConfigurationSuccess.json, test/unit/ngsiv2/httpBindings-test.js, test/unit/ngsiv2/startup-test.js, test/unit/ngsiv2/subscriptionRequests/configurationsMqttNotification.json, test/unit/ngsiv2/subscriptionRequests/configurationsMqttRequest.json, test/unit/ngsiv2/ultralightCommands-test.js, test/unit/ngsiv2/ultralightMeasures-test.js
From NGSI-v1 https://github.com/telefonicaid/iotagent-ul/blob/master/test/unit/httpBinding-test.js#L192 updated to NGSI-v2
(Copy pasted from PR #493)
This PRs is made with the aim of add all cases cover by NGSI-v1 tests to NGSI-v2 tests. This comment is intended to provide track of the changes needed:
=> Update NGSI-V2 tests (same as PR #493)

rpm/SOURCES/etc/init.d/iotaul
Fixes #214 (Starting at boot failed /etc/init.d/iotaul)
Required-Start: $local_fs $syslog $network
by
Required-Start: $local_fs $syslog $network $iotamanager
=> patch for the iotagent issue 214 according to the author i changed the line

test/unit/ngsiv2/mqttBinding-test.js
This PR is intended to restore some differences between tests that were deleted in NGSIv1 and were not present in NGSv2
=> Fix NGSIv2 under-covered scenarios

CHANGES_NEXT_RELEASE, docs/usermanual.md, lib/iotagent-ul.js, package.json
When a shutdown signal is sent, we need to do graceful shutdown out of Node.js and Express to avoid side effects
like finishing active requests before closing server, clean up resources, db connections etc.
see: https://stackfame.com/node-express-graceful-shutdown
=> Add graceful shutdown

CHANGES_NEXT_RELEASE, lib/commonBindings.js, package.json
Instead of applying the `explicitAttr` filtering at the south port (i.e. to the measures being received by IOTA), move the filtering to the north port (i.e. at the point in which the CB update request is built). That way every measure/attribute will be available in calculations done by JELX expressions, but only the ones explicitly provisioned will pass to the CB.
see  https://github.com/telefonicaid/iotagent-node-lib/pull/1157#issuecomment-993711890
Part of https://github.com/telefonicaid/iotagent-node-lib/issues/1151
=> Remove preprocess stripping of explicitAttrs

.readthedocs.yml, docs/requirements.txt, docs/usermanual.md
Related https://github.com/FIWARE/tutorials.NGSI-v2/pull/8
=> Add explicit protocol note for MQTT topics

CHANGES_NEXT_RELEASE, config.js, docs/installationguide.md, lib/bindings/AMQPBinding.js, lib/bindings/MQTTBinding.js, lib/configService.js, test/unit/startup-test.js
This avoids unnecessary polling to connect to MQTT and AMQP if they are not there and keeps the logs nice and clean.
As a side-effect, startup is quicker too.
Just add the following config to your docker-compose.
```
- IOTA_MQTT_DISABLED=true
- IOTA_AMPQ_DISABLED=true
```
Evil twin of https://github.com/telefonicaid/iotagent-json/pull/685
=> Add flags to disable MQTT and AMQP

CHANGES_NEXT_RELEASE, package.json, test/unit/ngsiv2/MQTT_commands_test.js, test/unit/ngsiv2/commandsAmqp-test.js, test/unit/ngsiv2/contextRequests/multipleMeasureProduction.json, test/unit/ngsiv2/contextRequests/singleMeasure.json, test/unit/ngsiv2/contextRequests/timeInstantDuplicated.json, test/unit/ngsiv2/contextRequests/timeInstantMeasures.json, test/unit/ngsiv2/contextRequests/timeInstantMeasures2.json, test/unit/ngsiv2/contextRequests/timestampMeasure.json, test/unit/ngsiv2/contextRequests/updateStatus2.json, test/unit/ngsiv2/httpBindings-test.js
twin PR https://github.com/telefonicaid/iotagent-json/pull/700
PR to test agent with new iota node lib:
If timestamp is provided as measure then no metadata with timestamp is added to attributes.
Compression about timestamp is always checked in iotagent-node-lib, so always is uncompressed
iota-node-lib deb should be set to #master before merge
=> use node lib refactor

CHANGES_NEXT_RELEASE, lib/iotaUtils.js
issue https://github.com/telefonicaid/iotagent-ul/issues/642
=> remove mergeDeviceWithConfiguration

CHANGES_NEXT_RELEASE, lib/iotaUtils.js
twin PR https://github.com/telefonicaid/iotagent-json/pull/816
=> Include device info in errors

CHANGES_NEXT_RELEASE, docs/usermanual.md, lib/bindings/HTTPBindings.js, lib/commonBindings.js, test/unit/ngsiv2/amqpBinding-test.js, test/unit/ngsiv2/contextRequests/multimeasure.json, test/unit/ngsiv2/contextRequests/multimeasure2.json, test/unit/ngsiv2/contextRequests/multimeasure3.json, test/unit/ngsiv2/httpBindings-test.js, test/unit/ngsiv2/mqttBinding-test.js
Twin PR of  https://github.com/telefonicaid/iotagent-json/pull/826
=> send to CB using multimeasures

CHANGES_NEXT_RELEASE, Changelog, docs/usermanual.md, lib/bindings/HTTPBindings.js, lib/constants.js
Twin PR https://github.com/telefonicaid/iotagent-json/pull/845
=> add response header about procesing time

CHANGES_NEXT_RELEASE, docs/usermanual.md, lib/bindings/HTTPBindings.js
Mimics https://github.com/telefonicaid/iotagent-json/pull/853 and https://github.com/telefonicaid/iotagent-json/pull/852
Needs: https://github.com/telefonicaid/iotagent-ul/pull/688
=> fix default transport

CHANGES_NEXT_RELEASE, lib/configService.js
Mimics https://github.com/telefonicaid/iotagent-json/pull/851
needs https://github.com/telefonicaid/iotagent-ul/pull/688
=> just print values for missed env vars at startup
